# Generated by Django 3.2.12 on 2022-03-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='code',
            field=models.CharField(max_length=12),
        ),
    ]
