# Generated by Django 3.2.12 on 2022-03-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_investment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
    ]
