# Generated by Django 3.2.12 on 2022-03-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_alter_investment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={},
        ),
    ]
