# Generated by Django 3.2.12 on 2022-08-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='cvv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cards',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
