# Generated by Django 3.2.12 on 2022-03-23 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_in_coin', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_in_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
