# Generated by Django 3.2.12 on 2022-05-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0003_affiliates_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliates',
            name='affiliate_ref',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='affiliates',
            name='credit_status',
            field=models.CharField(blank=True, default='Processing', max_length=10),
        ),
    ]
