# Generated by Django 3.2.12 on 2022-05-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0004_auto_20220521_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliates',
            name='affiliate_ref',
        ),
    ]
