# Generated by Django 3.2.12 on 2022-05-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0005_remove_affiliates_affiliate_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliates',
            name='affiliate_ref',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
