# Generated by Django 3.2.12 on 2022-03-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='current_bank_account',
            old_name='total_coins',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='interest_bank_account',
            old_name='total_interest_coins',
            new_name='amount',
        ),
    ]
