# Generated by Django 3.2.12 on 2022-04-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_withdrawal_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate_bank_account',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='current_bank_account',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='interest_bank_account',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal_bank_account',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
    ]
