# Generated by Django 3.2.12 on 2022-03-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='minimum_withdrawal',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=15),
            preserve_default=False,
        ),
    ]
