# Generated by Django 3.2.12 on 2022-03-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_rate_minimum_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='minimum_investment',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=15),
            preserve_default=False,
        ),
    ]
