# Generated by Django 3.2.12 on 2022-03-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_rate_minimum_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='withdrawal_fee',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=15),
            preserve_default=False,
        ),
    ]
