# Generated by Django 3.2.12 on 2022-03-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_rate_withdrawal_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
