# Generated by Django 3.2.12 on 2022-03-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0005_alter_rate_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='withdrawal_fee',
            field=models.DecimalField(decimal_places=1, max_digits=15),
        ),
    ]
