# Generated by Django 3.2.12 on 2022-03-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0006_alter_rate_withdrawal_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='fake',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
