# Generated by Django 3.2.12 on 2022-04-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0008_auto_20220401_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='affiliate_allowed_bonus',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
