# Generated by Django 3.2.12 on 2022-03-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20220307_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coin_id',
            field=models.CharField(default='id', max_length=12),
            preserve_default=False,
        ),
    ]
