# Generated by Django 3.2.12 on 2022-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_alter_setting_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='alfacoins_id',
            field=models.CharField(max_length=50),
        ),
    ]
