# Generated by Django 3.2.12 on 2022-03-25 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_coin_alfacoins_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.coin', verbose_name='Coin'),
        ),
    ]
