# Generated by Django 3.2.12 on 2022-03-25 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_alter_setting_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='coin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='settings.coin', verbose_name='Coin'),
        ),
    ]
