# Generated by Django 3.2.12 on 2022-03-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='amount_in_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
